version: 2
project_name: ikea-dirigera-exporter

before:
  hooks:
    - go mod tidy

builds:
  - id: ikea-dirigera-exporter
    main: cmd/main.go
    binary: exporter
    ldflags:
      - -s -w
      - -X github.com/salex-org/ikea-dirigera-exporter/cmd.version={{ .Version }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "7"

dockers_v2:
  - images:
      - ghcr.io/salex-org/ikea-dirigera-exporter
    tags:
      - "{{ .Version }}"
      - "latest"
    dockerfile: Dockerfile
    platforms:
      - linux/amd64
      - linux/arm64
      - linux/arm/v7

archives:
  - formats: [ 'tar.gz' ]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: salex-org
    name: ikea-dirigera-exporter
  draft: false
  prerelease: false

snapshot:
  version_template: "v{{ incpatch .Version }}-snapshot"
